TARGET=writeup
HTML=main_html
CC=icc
CFLAGS=-std=c99 -Wall -lrt -pthread
SRC=${TARGET}

all: pdf thread shmem

#both: dvi ps pdf

dvi: ${TARGET}.tex 
#	pygmentize the input source file -- THIS NAME SHOULD BE SAFE
#	pygmentize -f latex -o __${TARGET}.tex ${TARGET}.tex
#	run latex twice to get references correct
	latex ${TARGET}.tex
#	you can also have a bibtex line here
#	bibtex $(TARGET)
	latex $(TARGET).tex
#	remove the pygmentized output to avoid cluttering up the directory
#	rm __${TARGET}.tex

ps: dvi
	dvips -R -Poutline -t letter ${TARGET}.dvi -o ${TARGET}.ps


pdf: ps
	ps2pdf ${TARGET}.ps
	rm ${TARGET}.log
	rm ${TARGET}.aux
	rm ${TARGET}.dvi
	rm ${TARGET}.ps


thread: 
	$(CC) $(CFLAGS) threaded_sieve.c linked_list.c
	mv a.out threadsieve

shmem: 
	$(CC) $(CFLAGS) shmem_sieve.c linked_list.c
	mv a.out shmemsieve
